"use client";
import { useActionState } from "react";
import { Clock,Lock,Play,RotateCcw,Save } from "lucide-react";
import { configureVoting,lockVoting,reopenVoting,startFinalRound } from "@/actions/voting";
import { effectiveVotingState,usesSecondRound } from "@/lib/voting-lifecycle";
import type { Trip } from "@/lib/types";

export function VotingSettings({trip,listingCount}:{trip:Trip;listingCount:number}){
  const action=configureVoting.bind(null,trip.inviteCode);const[state,formAction,pending]=useActionState(action,{message:""});const votingState=effectiveVotingState(trip);const locked=votingState.endsWith("LOCKED");const canStartFinal=votingState==="ROUND_1_LOCKED"&&usesSecondRound(trip,listingCount);
  const deadline=trip.votingDeadline?new Date(trip.votingDeadline):null;const localDeadline=deadline?new Date(deadline.getTime()-deadline.getTimezoneOffset()*60_000).toISOString().slice(0,16):"";
  return <section className="mt-7 rounded-[2rem] border border-[#e3e0d8] bg-white p-5 sm:p-8"><div className="flex items-center gap-3"><Clock className="text-[#1f7168]"/><div><h2 className="text-xl font-extrabold">Voting rounds</h2><p className="text-sm text-[#63716d]">Current state: {votingState.toLowerCase().replaceAll("_"," ")}</p></div></div><form action={formAction} className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Voting format<select name="votingMode" defaultValue={trip.votingMode??"AUTO"} className="mt-2 min-h-12 w-full rounded-xl border border-[#dcded8] bg-white px-3 text-[16px]"><option value="AUTO">Automatic by listing count</option><option value="SINGLE">Single round</option><option value="TWO_ROUND">Always use two rounds</option></select></label><label className="text-sm font-bold">Automatic lock time<input name="votingDeadline" type="datetime-local" defaultValue={localDeadline} className="mt-2 min-h-12 w-full rounded-xl border border-[#dcded8] bg-white px-3 text-[16px]"/><input type="hidden" name="timezoneOffset" value={new Date().getTimezoneOffset()}/></label>{state.message&&<p className="text-sm font-semibold text-[#1f7168] sm:col-span-2">{state.message}</p>}<button disabled={pending} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-[#18342f] px-5 text-sm font-bold text-white"><Save size={16}/>Save voting settings</button></form><div className="mt-5 flex flex-wrap gap-2">{locked?<form action={reopenVoting.bind(null,trip.inviteCode)}><button className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#cfd8d4] px-5 text-sm font-bold"><RotateCcw size={16}/>Reopen this round</button></form>:<form action={lockVoting.bind(null,trip.inviteCode)}><button className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#b6422d] px-5 text-sm font-bold text-white"><Lock size={16}/>Lock voting now</button></form>}{canStartFinal&&<form action={startFinalRound.bind(null,trip.inviteCode)}><button className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#1f7168] px-5 text-sm font-bold text-white"><Play size={16}/>Select finalists and open round 2</button></form>}</div><p className="mt-4 text-xs leading-5 text-[#71807c]">Automatic mode uses one round for 5 or fewer listings, top 3 for 6–10, and top 5 for more than 10. Server time decides whether a deadline has passed.</p></section>;
}
