import { notFound,redirect } from "next/navigation";
import { UserRound,Vote } from "lucide-react";
import { TripHeader } from "@/components/trip/TripHeader";
import { TripNavigation } from "@/components/trip/TripNavigation";
import { isTripCreator } from "@/lib/creator-session";
import { readDatabase } from "@/lib/db";
import { getCurrentParticipant } from "@/lib/participant-session";
import { RemoveParticipantButton } from "@/components/participant/RemoveParticipantButton";

export default async function ParticipantsPage({params}:{params:Promise<{tripId:string}>}){const{tripId}=await params;const database=await readDatabase();const trip=database.trips.find((item)=>item.inviteCode===tripId);if(!trip)notFound();const creator=await isTripCreator(trip);const current=await getCurrentParticipant(trip,database);if(!creator&&!current)redirect(`/trip/${tripId}/join`);const participants=database.participants.filter((item)=>item.tripId===trip.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));return <main className="min-h-screen"><TripHeader trip={trip} isCreator={creator}/><TripNavigation inviteCode={tripId} active="participants"/><section className="mx-auto max-w-5xl px-4 py-9 sm:px-8 sm:py-12"><div className="flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[.15em] text-[#1f7168]">The travel crew</p><h2 className="display-font mt-1 text-4xl">Participants</h2><p className="mt-3 text-[#63716d]">Signed-in participants can return from another browser; guests remain tied to their original browser.</p></div><span className="rounded-full bg-[#e7f1ed] px-3 py-1.5 text-sm font-extrabold text-[#285f54]">{participants.length}/{trip.travellerCount} joined</span></div>{participants.length?<div className="mt-8 grid gap-4 sm:grid-cols-2">{participants.map((participant,index)=>{const voteCount=database.votes.filter((vote)=>vote.participantId===participant.id).length;return <article key={participant.id} className={`flex items-center gap-4 rounded-2xl border p-4 shadow-sm ${participant.id===current?.id?"border-[#9fc9bc] bg-[#edf7f3]":"border-[#e3e0d8] bg-white"}`}><span className={`grid size-12 shrink-0 place-items-center rounded-full text-lg font-extrabold text-white ${["bg-[#e85d3f]","bg-[#1f7168]","bg-[#735da5]","bg-[#bd7b2f]"][index%4]}`}>{participant.name.slice(0,1).toUpperCase()}</span><div className="min-w-0 flex-1"><h3 className="truncate font-bold">{participant.name}{participant.id===current?.id&&<span className="ml-2 text-xs text-[#1f7168]">You</span>}{participant.userId&&<span className="ml-2 text-xs text-[#63716d]">Google linked</span>}</h3><p className="mt-1 flex items-center gap-1.5 text-sm text-[#71807c]"><Vote size={14}/>{voteCount} vote{voteCount===1?"":"s"}</p></div>{creator&&participant.id!==current?.id&&<RemoveParticipantButton inviteCode={tripId} participantId={participant.id} name={participant.name}/>}</article>})}</div>:<div className="mt-8 rounded-[2rem] border border-dashed border-[#cfd8d4] bg-white px-6 py-14 text-center"><UserRound className="mx-auto text-[#7f938c]" size={34}/><h3 className="display-font mt-4 text-2xl">No one has joined yet</h3><p className="mt-2 text-[#63716d]">Share the trip link to bring your group in.</p></div>}</section></main>}
