import { notFound,redirect } from "next/navigation";
import { ComparisonView,type ComparisonListing } from "@/components/compare/ComparisonView";
import { TripHeader } from "@/components/trip/TripHeader";
import { TripNavigation } from "@/components/trip/TripNavigation";
import { isTripCreator } from "@/lib/creator-session";
import { readDatabase } from "@/lib/db";
import { getCurrentParticipant } from "@/lib/participant-session";
import { countVotes } from "@/lib/ranking";
import { calculateRecommendations } from "@/lib/recommendations";

export default async function ComparePage({params}:{params:Promise<{tripId:string}>}){const{tripId}=await params;const database=await readDatabase();const trip=database.trips.find((item)=>item.inviteCode===tripId);if(!trip)notFound();const creator=await isTripCreator(trip);const participant=await getCurrentParticipant(trip,database);if(!creator&&!participant)redirect(`/trip/${tripId}/join`);const tripParticipants=database.participants.filter((item)=>item.tripId===trip.id);const rawListings=database.listings.filter((item)=>item.tripId===trip.id);const listingIds=new Set(rawListings.map((item)=>item.id));const tripVotes=database.votes.filter((item)=>listingIds.has(item.listingId));const participantIds=new Set(tripParticipants.map((item)=>item.id));const scores=calculateRecommendations({listings:rawListings,amenities:database.amenities,listingAmenities:database.listingAmenities,votes:tripVotes,participantCount:tripParticipants.length,preferences:database.preferences,participantPreferences:database.participantPreferences.filter((item)=>participantIds.has(item.participantId))});const listings:ComparisonListing[]=rawListings.map((listing)=>{const votes=tripVotes.filter((item)=>item.listingId===listing.id);const amenityIds=database.listingAmenities.filter((item)=>item.listingId===listing.id).map((item)=>item.amenityId);return{id:listing.id,propertyName:listing.propertyName,imageUrl:listing.imageUrl,platform:listing.platform,totalPrice:listing.totalPrice,currency:listing.currency,pricePerPerson:listing.totalPrice/trip.travellerCount,rating:listing.rating,reviewCount:listing.reviewCount,maxGuests:listing.maxGuests,bedrooms:listing.bedrooms,beds:listing.beds,bathrooms:listing.bathrooms,location:listing.location,amenities:database.amenities.filter((item)=>amenityIds.includes(item.id)),voteCounts:countVotes(votes),score:scores.get(listing.id)!.combinedScore}});const selectedName=rawListings.find((item)=>item.id===trip.selectedListingId)?.propertyName;return <main className="min-h-screen"><TripHeader trip={trip} isCreator={creator} selectedListingName={selectedName}/><TripNavigation inviteCode={tripId} active="compare"/><section className="mx-auto max-w-7xl px-4 py-9 sm:px-8 lg:px-12"><p className="text-sm font-bold uppercase tracking-[.15em] text-[#1f7168]">Side by side</p><h1 className="display-font mt-1 text-4xl sm:text-5xl">Compare stays</h1><p className="mt-3 max-w-2xl text-[#63716d]">Choose up to four options. Lowest price and highest rating are highlighted when available.</p><div className="mt-8"><ComparisonView listings={listings}/></div></section></main>}
