import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight,CalendarDays,MapPin,Plus } from "lucide-react";
import { auth } from "@/auth";
import { AuthButton } from "@/components/auth/AuthButton";
import { Logo } from "@/components/brand/Logo";
import { getCreatorTrips } from "@/lib/creator-session";
import { readDatabase } from "@/lib/db";
import { formatTripDates } from "@/lib/format";
import { groupTrips,type TripLifecycle } from "@/lib/trip-lifecycle";
const labels:Record<TripLifecycle,{title:string;copy:string}>={ACTIVE:{title:"Active trips",copy:"Upcoming and currently running plans."},PAST:{title:"Past trips",copy:"Automatically placed here after their end date."},COMPLETED:{title:"Completed",copy:"Trips you have personally marked complete."}};
export default async function TripsPage(){if(!(await auth())?.user)redirect("/login");const database=await readDatabase();const groups=groupTrips((await getCreatorTrips(database)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)));return <main className="min-h-screen"><header className="border-b border-[#e8e2d8] bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-4 sm:px-8"><Link href="/"><Logo/></Link><div className="flex items-center gap-2"><AuthButton/><Link href="/trips/new" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#e85d3f] px-4 text-sm font-bold text-white"><Plus size={17}/>New trip</Link></div></div></header><section className="mx-auto max-w-6xl px-4 py-10 sm:px-8 sm:py-14"><p className="text-sm font-bold uppercase tracking-[.15em] text-[#e85d3f]">Creator dashboard</p><h1 className="display-font mt-1 text-5xl">All your trips</h1><p className="mt-3 text-[#63716d]">One account can own and manage as many trips as you need.</p>{(["ACTIVE","PAST","COMPLETED"] as TripLifecycle[]).map((status)=>{const trips=groups[status];return <section key={status} className="mt-10"><div className="flex items-end justify-between border-b border-[#dedbd4] pb-3"><div><h2 className="text-xl font-extrabold">{labels[status].title}</h2><p className="text-sm text-[#71807c]">{labels[status].copy}</p></div><span className="text-sm font-bold text-[#63716d]">{trips.length}</span></div>{trips.length?<div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{trips.map((trip)=>{const count=database.listings.filter((item)=>item.tripId===trip.id).length;return <Link key={trip.id} href={`/trip/${trip.inviteCode}`} className="group rounded-[1.5rem] border border-[#e3e0d8] bg-white p-5 shadow-sm transition hover:-translate-y-0.5"><div className="flex justify-between gap-3"><h3 className="text-xl font-extrabold">{trip.name}</h3><ArrowRight className="shrink-0" size={18}/></div><p className="mt-4 flex items-center gap-2 text-sm text-[#63716d]"><MapPin size={15}/>{trip.destination}</p><p className="mt-2 flex items-center gap-2 text-sm text-[#63716d]"><CalendarDays size={15}/>{formatTripDates(trip.startDate,trip.endDate)}</p><p className="mt-5 text-sm font-bold text-[#1f7168]">{count} stay{count===1?"":"s"}</p></Link>})}</div>:<p className="mt-4 rounded-2xl border border-dashed border-[#d8d5ce] p-6 text-sm text-[#71807c]">No {labels[status].title.toLowerCase()}.</p>}</section>})}</section></main>}
