import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, CalendarDays, MapPin, Medal, Plus, Users } from "lucide-react";
import { auth } from "@/auth";
import { AuthButton } from "@/components/auth/AuthButton";
import { Logo } from "@/components/brand/Logo";
import { achievementsForUser } from "@/lib/achievements";
import { getCreatorTrips } from "@/lib/creator-session";
import { readDatabase } from "@/lib/db";
import { formatTripDates } from "@/lib/format";
import { groupTrips, type TripLifecycle } from "@/lib/trip-lifecycle";

const labels:Record<TripLifecycle,{title:string;copy:string}>={ACTIVE:{title:"Active trips",copy:"Upcoming and currently running plans."},PAST:{title:"Past trips",copy:"Trips whose end date has passed."},COMPLETED:{title:"Completed",copy:"Trips confirmed as successfully completed."},CANCELLED:{title:"Cancelled",copy:"Plans that changed, preserved with their history."}};

export default async function TripsPage(){
  const session=await auth();if(!session?.user?.id)redirect("/login");
  const database=await readDatabase();const accessible=await getCreatorTrips(database);const groups=groupTrips(accessible.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)));const achievements=achievementsForUser(database,session.user.id);const unlocked=achievements.filter((item)=>item.unlocked);const next=achievements.filter((item)=>!item.unlocked).sort((a,b)=>(b.progress/b.target)-(a.progress/a.target)).slice(0,3);
  return <main className="min-h-screen"><header className="border-b border-[#e8e2d8] bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-4 sm:px-8"><Link href="/"><Logo/></Link><div className="flex items-center gap-2"><AuthButton/><Link href="/trips/new" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#e85d3f] px-4 text-sm font-bold text-white"><Plus size={17}/>New trip</Link></div></div></header><section className="mx-auto max-w-6xl px-4 py-10 sm:px-8 sm:py-14"><p className="text-sm font-bold uppercase tracking-[.15em] text-[#e85d3f]">Your travel history</p><h1 className="display-font mt-1 text-5xl">Your trips</h1><p className="mt-3 text-[#63716d]">Trips you host and trips you join follow your Google account across devices.</p>
    <section className="mt-8 rounded-[2rem] bg-[#18342f] p-5 text-white sm:p-7"><div className="flex items-center gap-3"><Medal className="text-[#f3b75f]"/><div><h2 className="text-xl font-extrabold">Achievements</h2><p className="text-sm text-[#b8cbc6]">{unlocked.length} unlocked · meaningful completed activity only</p></div></div><div className="mt-5 flex flex-wrap gap-2">{unlocked.length?unlocked.map((item)=><span key={item.id} title={item.description} className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold">{item.medal==="GOLD"?"🥇":item.medal==="SILVER"?"🥈":item.medal==="BRONZE"?"🥉":"🏅"} {item.title}</span>):<span className="text-sm text-[#b8cbc6]">Complete your first qualifying trip to earn First Takeoff.</span>}</div>{next.length>0&&<div className="mt-5 grid gap-2 sm:grid-cols-3">{next.map((item)=><div key={item.id} className="rounded-xl bg-white/5 p-3 text-xs"><b>{item.title}</b><p className="mt-1 text-[#b8cbc6]">{item.progress} / {item.target} · {item.description}</p></div>)}</div>}</section>
    {(["ACTIVE","PAST","COMPLETED","CANCELLED"] as TripLifecycle[]).map((status)=>{const trips=groups[status];return <section key={status} className="mt-10"><div className="flex items-end justify-between border-b border-[#dedbd4] pb-3"><div><h2 className="text-xl font-extrabold">{labels[status].title}</h2><p className="text-sm text-[#71807c]">{labels[status].copy}</p></div><span className="text-sm font-bold text-[#63716d]">{trips.length}</span></div>{trips.length?<div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{trips.map((trip)=>{const count=database.listings.filter((item)=>item.tripId===trip.id).length;const host=trip.creatorUserId===session.user.id;return <Link key={trip.id} href={`/trip/${trip.inviteCode}`} className="group rounded-[1.5rem] border border-[#e3e0d8] bg-white p-5 shadow-sm transition hover:-translate-y-0.5"><div className="flex justify-between gap-3"><div><span className={`rounded-full px-2 py-1 text-[11px] font-extrabold ${host?"bg-[#e7f1ed] text-[#1f7168]":"bg-[#fff0eb] text-[#a64a36]"}`}>{host?"Hosting":"Joined"}</span><h3 className="mt-2 text-xl font-extrabold">{trip.name}</h3></div><ArrowRight className="shrink-0" size={18}/></div><p className="mt-4 flex items-center gap-2 text-sm text-[#63716d]"><MapPin size={15}/>{trip.destination}</p><p className="mt-2 flex items-center gap-2 text-sm text-[#63716d]"><CalendarDays size={15}/>{formatTripDates(trip.startDate,trip.endDate)}</p><p className="mt-5 flex items-center gap-2 text-sm font-bold text-[#1f7168]"><Users size={15}/>{count} stay{count===1?"":"s"}</p></Link>})}</div>:<p className="mt-4 rounded-2xl border border-dashed border-[#d8d5ce] p-6 text-sm text-[#71807c]">No {labels[status].title.toLowerCase()}.</p>}</section>})}</section></main>;
}
