import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarDays, Check, Heart, Link2, MapPin, MessageCircle, Sparkles, Users, Vote } from "lucide-react";
import { Logo } from "@/components/brand/Logo";
import { getCreatorTrips } from "@/lib/creator-session";
import { readDatabase } from "@/lib/db";
import { formatTripDates } from "@/lib/format";
import { openSeededTripAsCreator } from "@/actions/demo";
import { SEEDED_TRIP_INVITE_CODE } from "@/lib/seed-constants";
import { AuthButton } from "@/components/auth/AuthButton";

const stays = [
  ["Casa Sol","Candolim, Goa","₹4,000 / person","92%","https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=1000&q=85","left-0 top-20 z-20 -rotate-3"],
  ["The Palm House","Anjuna, Goa","₹3,650 / person","87%","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85","right-0 top-0 z-10 rotate-2"],
  ["Salt & Sky Villa","Vagator, Goa","₹4,400 / person","81%","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85","bottom-0 right-[12%] z-30 -rotate-1"],
];

export default async function Home() {
  const database=await readDatabase();
  const creatorTrips=(await getCreatorTrips(database)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
  const seededDemo=process.env.NODE_ENV!=="production"&&!creatorTrips.some((trip)=>trip.inviteCode===SEEDED_TRIP_INVITE_CODE)?database.trips.find((trip)=>trip.inviteCode===SEEDED_TRIP_INVITE_CODE):undefined;
  return <main className="min-h-screen overflow-hidden">
    <nav className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-4 sm:px-8 sm:py-5 lg:px-12"><Logo/><div className="flex shrink-0 items-center gap-2 sm:gap-3">{creatorTrips.length>0&&<Link href={creatorTrips.length===1?`/trip/${creatorTrips[0].inviteCode}`:"#my-trips"} className="hidden min-h-11 items-center whitespace-nowrap rounded-full border border-[#d8dfdc] bg-white px-3 text-sm font-bold hover:border-[#a9bbb5] sm:inline-flex sm:px-4">{creatorTrips.length===1?"Back to trip":"My trips"}</Link>}<Link href="#how-it-works" className="hidden min-h-11 items-center px-4 py-2 text-sm font-semibold lg:flex">How it works</Link><AuthButton/><Link href="/trips/new" className="inline-flex min-h-11 items-center whitespace-nowrap rounded-full bg-[#18342f] px-3 py-2.5 text-sm font-bold text-white hover:bg-[#285048] sm:px-5">Plan a trip</Link></div></nav>
    <section className="mx-auto grid max-w-7xl items-center gap-10 px-4 pb-20 pt-10 sm:gap-14 sm:px-8 sm:pb-24 sm:pt-14 lg:grid-cols-[.9fr_1.1fr] lg:px-12 lg:pb-32 lg:pt-20">
      <div className="relative z-10"><div className="mb-5 inline-flex max-w-full items-center gap-2 rounded-full border border-[#eadaca] bg-white/80 px-3.5 py-2 text-xs font-bold text-[#8b513f] shadow-sm sm:mb-6 sm:px-4 sm:text-sm"><Sparkles className="shrink-0" size={15}/> <span>Group trips, minus the group-chat chaos</span></div><h1 className="display-font max-w-2xl text-[3.35rem] font-medium leading-[.94] tracking-[-.045em] min-[380px]:text-6xl sm:text-7xl lg:text-[5.7rem]">Find the stay <span className="italic text-[#e85d3f]">everyone</span> loves.</h1><p className="mt-6 max-w-xl text-base leading-7 text-[#63716d] sm:mt-7 sm:text-xl sm:leading-8">Gather links from any booking site, compare the details, and let every friend have their say—all in one beautiful place.</p><div className="mt-8 flex flex-col gap-3 sm:mt-9 sm:flex-row"><Link href="/trips/new" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#e85d3f] px-7 py-3.5 font-bold text-white shadow-[0_12px_30px_rgba(232,93,63,.25)] transition hover:-translate-y-0.5 hover:bg-[#c7442b]">Start planning free <ArrowRight size={18}/></Link><span className="flex min-h-11 items-center justify-center gap-2 px-4 text-sm font-medium text-[#63716d]"><Check size={17} className="text-[#1f7168]"/> No accounts for friends</span></div></div>
      <div className="mobile-stay-stack relative min-h-[460px] sm:min-h-[540px]" aria-label="Example accommodation shortlist"><div className="absolute -right-24 top-0 size-[430px] rounded-full bg-[#d7ebe6] blur-3xl"/><div className="absolute -bottom-20 left-0 size-72 rounded-full bg-[#f7dacb] blur-3xl"/>{stays.map(([title,place,price,score,src,position],i)=><article key={title} className={`absolute w-[76%] max-w-[330px] overflow-hidden rounded-[1.5rem] border-[5px] border-white bg-white shadow-[0_24px_70px_rgba(29,61,54,.18)] sm:w-[70%] sm:rounded-[1.75rem] sm:border-[6px] ${position}`}><div className="relative h-44 min-[380px]:h-48 sm:h-56"><Image src={src} alt="" fill sizes="(max-width: 640px) 76vw, 330px" className="object-cover" priority={i===0}/></div><div className="p-3.5 sm:p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h2 className="truncate font-bold">{title}</h2><p className="truncate text-sm text-[#71807c]">{place}</p></div><span className="shrink-0 rounded-full bg-[#e4f2ee] px-2.5 py-1 text-xs font-bold text-[#1f7168]">{score}</span></div><div className="mt-3 flex items-center justify-between gap-2 border-t border-[#eeeae3] pt-3 text-xs min-[380px]:text-sm"><strong className="truncate">{price}</strong><span className="flex shrink-0 items-center gap-1 text-[#e85d3f]"><Heart size={15} fill="currentColor"/> 5</span></div></div></article>)}</div>
    </section>
    {(creatorTrips.length>0||seededDemo)&&<section id="my-trips" className="border-y border-[#e8e2d8] bg-white px-4 py-16 sm:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.15em] text-[#e85d3f]">Welcome back</p><h2 className="display-font mt-1 text-4xl sm:text-5xl">Your trips</h2><p className="mt-3 text-[#63716d]">Continue planning a trip created on this device.</p></div><Link href="/trips/new" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-[#d7deda] px-5 text-sm font-bold">Create another <ArrowRight size={16}/></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{creatorTrips.map((trip)=>{const stayCount=database.listings.filter((listing)=>listing.tripId===trip.id).length;return <Link key={trip.id} href={`/trip/${trip.inviteCode}`} className="group rounded-[1.5rem] border border-[#e3e0d8] bg-[#fbfaf7] p-5 transition hover:-translate-y-0.5 hover:border-[#b8cbc4] hover:shadow-lg"><div className="flex items-start justify-between gap-3"><h3 className="text-xl font-extrabold">{trip.name}</h3><ArrowRight className="shrink-0 transition group-hover:translate-x-1" size={19}/></div><div className="mt-4 space-y-2 text-sm text-[#63716d]"><p className="flex items-center gap-2"><MapPin size={15}/>{trip.destination}</p><p className="flex items-center gap-2"><CalendarDays size={15}/>{formatTripDates(trip.startDate,trip.endDate)}</p></div><p className="mt-5 text-sm font-bold text-[#1f7168]">{stayCount} stay{stayCount===1?"":"s"} shortlisted</p></Link>})}{seededDemo&&<form action={openSeededTripAsCreator} className="rounded-[1.5rem] border border-dashed border-[#e2a96a] bg-[#fff9ed] p-5"><span className="rounded-full bg-[#f5dfb9] px-2.5 py-1 text-xs font-extrabold text-[#7d5521]">Development demo</span><h3 className="mt-4 text-xl font-extrabold">{seededDemo.name}</h3><div className="mt-4 space-y-2 text-sm text-[#63716d]"><p className="flex items-center gap-2"><MapPin size={15}/>{seededDemo.destination}</p><p className="flex items-center gap-2"><CalendarDays size={15}/>{formatTripDates(seededDemo.startDate,seededDemo.endDate)}</p></div><button className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-full bg-[#18342f] px-5 text-sm font-bold text-white">Open as creator <ArrowRight size={16}/></button></form>}</div></div></section>}
    <section id="how-it-works" className="bg-[#18342f] px-5 py-20 text-white sm:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#9dc9be]">One shared shortlist</p><div className="mt-3 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="display-font max-w-2xl text-4xl leading-tight sm:text-5xl">From scattered links to one clear winner.</h2><p className="max-w-sm text-[#b8cbc6]">Built for real groups making real decisions—not spreadsheets and endless polls.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-3xl bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{[[Link2,"Collect","Paste stays from Airbnb, Booking.com, Agoda, or anywhere else."],[Users,"Invite","Share one link. Friends join with just their name."],[Vote,"Decide","Vote Love, Like, Maybe, or No on every option."],[MessageCircle,"Choose","Compare details and understand the group's favorite."]].map(([Icon,title,copy],i)=>{const I=Icon as typeof Link2;return <article key={title as string} className="bg-[#18342f] p-7 sm:p-8"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-white/10 text-[#f5b09e]"><I size={21}/></span><span className="text-sm text-white/35">0{i+1}</span></div><h3 className="mt-8 text-xl font-bold">{title as string}</h3><p className="mt-2 leading-7 text-[#aebfbb]">{copy as string}</p></article>})}</div></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-9 text-sm text-[#63716d] sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-12"><Logo/><p>Made for better trips and fewer group-chat debates.</p></footer>
  </main>;
}
