import { beforeEach,describe,expect,it,vi } from "vitest";
import type { Database,Trip } from "@/lib/types";

const mocks=vi.hoisted(()=>({auth:vi.fn(),get:vi.fn(),set:vi.fn()}));
vi.mock("@/auth",()=>({auth:mocks.auth}));
vi.mock("next/headers",()=>({cookies:vi.fn(async()=>({get:mocks.get,set:mocks.set}))}));
import { getCreatorTrips,getCreatorUserId,hashToken,isTripCreator,setCreatorSession } from "@/lib/creator-session";

const trip=(id:string,overrides:Partial<Trip>={}):Trip=>({id,inviteCode:id,name:id,destination:"Goa",startDate:"2026-01-01",endDate:"2026-01-02",travellerCount:2,accommodationBudget:null,currency:"INR",creatorUserId:null,creatorTokenHash:"",status:"ACTIVE",completedAt:null,selectedListingId:null,createdAt:"",updatedAt:"",...overrides});
const database=(trips:Trip[]):Database=>({users:[],trips,participants:[],listings:[],amenities:[],listingAmenities:[],votes:[],comments:[],preferences:[],participantPreferences:[],activityEvents:[]});

describe("creator sessions",()=>{beforeEach(()=>{vi.clearAllMocks();mocks.auth.mockResolvedValue(null);mocks.get.mockReturnValue(undefined)});it("hashes tokens deterministically",()=>{expect(hashToken("secret")).toBe(hashToken("secret"));expect(hashToken("secret")).not.toBe(hashToken("other"))});it("sets a secure creator cookie in production",async()=>{vi.stubEnv("NODE_ENV","production");await setCreatorSession("trip","token");expect(mocks.set).toHaveBeenCalledWith("roamly_creator_trip","token",expect.objectContaining({httpOnly:true,secure:true,path:"/"}));vi.unstubAllEnvs()});it("recognizes account ownership before checking cookies",async()=>{mocks.auth.mockResolvedValue({user:{id:"u1"}});expect(await isTripCreator(trip("t",{creatorUserId:"u1"}))).toBe(true);expect(mocks.get).not.toHaveBeenCalled()});it("supports matching legacy creator cookies",async()=>{mocks.get.mockReturnValue({value:"legacy"});expect(await isTripCreator(trip("t",{creatorTokenHash:hashToken("legacy")}))).toBe(true)});it("rejects missing, incorrect, and malformed legacy credentials",async()=>{expect(await isTripCreator(trip("t"))).toBe(false);mocks.get.mockReturnValue({value:"wrong"});expect(await isTripCreator(trip("t",{creatorTokenHash:hashToken("right")}))).toBe(false);expect(await isTripCreator(trip("t",{creatorTokenHash:"x"}))).toBe(false)});it("collects hosted, joined, and legacy-owned trips",async()=>{mocks.auth.mockResolvedValue({user:{id:"u1"}});mocks.get.mockImplementation((name:string)=>name.endsWith("legacy")?{value:"token"}:undefined);const value=database([trip("account",{creatorUserId:"u1"}),trip("joined"),trip("legacy",{creatorTokenHash:hashToken("token")}),trip("other")]);value.participants.push({id:"p",tripId:"joined",name:"Guest",sessionHash:"",userId:"u1",createdAt:"",updatedAt:""});const result=await getCreatorTrips(value);expect(result.map((item)=>item.id)).toEqual(["account","joined","legacy"])});it("returns the signed-in creator id",async()=>{expect(await getCreatorUserId()).toBeNull();mocks.auth.mockResolvedValue({user:{id:"u1"}});expect(await getCreatorUserId()).toBe("u1")});});
