import { beforeEach,describe,expect,it,vi } from "vitest";

const fsMocks=vi.hoisted(()=>({mkdir:vi.fn(),readFile:vi.fn(),rename:vi.fn(),writeFile:vi.fn()}));
vi.mock("node:fs/promises",()=>fsMocks);
import { emptyDatabase,findTripByInviteCode,parseDatabaseDocument,readDatabase,updateDatabase,writeDatabase } from "@/lib/db";

describe("database document validation",()=>{it("rejects invalid shapes",()=>{expect(()=>parseDatabaseDocument(null)).toThrow("must be an object");expect(()=>parseDatabaseDocument({trips:{}})).toThrow('field "trips" must be an array')});it("rejects malformed array entries with a controlled error",()=>{expect(()=>parseDatabaseDocument({trips:[null]})).toThrow('entry "trips[0]" must be an object');expect(()=>parseDatabaseDocument({trips:[{}]})).toThrow('entry "trips[0]" is missing required field "id"')});});

describe("JSON database",()=>{beforeEach(()=>vi.clearAllMocks());it("builds a complete empty document",()=>expect(emptyDatabase()).toEqual({users:[],trips:[],participants:[],listings:[],amenities:[],listingAmenities:[],votes:[],comments:[],preferences:[],participantPreferences:[]}));it("returns an empty database when the file is absent",async()=>{fsMocks.readFile.mockRejectedValue(Object.assign(new Error("missing"),{code:"ENOENT"}));expect(await readDatabase()).toEqual(emptyDatabase())});it("rethrows unexpected read errors",async()=>{fsMocks.readFile.mockRejectedValue(new Error("denied"));await expect(readDatabase()).rejects.toThrow("denied")});it("normalizes data written by earlier app versions",async()=>{fsMocks.readFile.mockResolvedValue(JSON.stringify({trips:[{id:"t",inviteCode:"code",name:"Trip",destination:"Goa",startDate:"2026-01-01",endDate:"2026-01-02",travellerCount:2,accommodationBudget:null,currency:"INR",selectedListingId:null,createdAt:"",updatedAt:""}]}));const result=await readDatabase();expect(result.users).toEqual([]);expect(result.trips[0]).toMatchObject({creatorUserId:null,creatorTokenHash:"",status:"ACTIVE",completedAt:null})});it("writes atomically through a temporary file",async()=>{await writeDatabase(emptyDatabase());expect(fsMocks.mkdir).toHaveBeenCalledWith(expect.stringContaining("data"),{recursive:true});expect(fsMocks.writeFile).toHaveBeenCalledWith(expect.stringContaining("db.tmp.json"),expect.stringContaining('"users": []'),"utf8");expect(fsMocks.rename).toHaveBeenCalledWith(expect.stringContaining("db.tmp.json"),expect.stringContaining("db.json"))});it("updates and persists a database mutation",async()=>{fsMocks.readFile.mockResolvedValue(JSON.stringify(emptyDatabase()));const result=await updateDatabase((data)=>{data.preferences.push({id:"p",key:"pool",label:"Pool",description:null,createdAt:""});return "done"});expect(result).toBe("done");expect(fsMocks.writeFile).toHaveBeenCalledWith(expect.any(String),expect.stringContaining('"label": "Pool"'),"utf8")});it("finds trips by invite code",async()=>{fsMocks.readFile.mockResolvedValue(JSON.stringify({...emptyDatabase(),trips:[{id:"t",inviteCode:"goa",name:"Trip",destination:"Goa",startDate:"2026-01-01",endDate:"2026-01-02",travellerCount:2,accommodationBudget:null,currency:"INR",creatorUserId:null,creatorTokenHash:"",status:"ACTIVE",completedAt:null,selectedListingId:null,createdAt:"",updatedAt:""}]}));expect((await findTripByInviteCode("goa"))?.id).toBe("t");expect(await findTripByInviteCode("missing")).toBeNull()});});
