import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
const mocks=vi.hoisted(()=>({lookup:vi.fn()}));
vi.mock("node:dns/promises",()=>({lookup:mocks.lookup}));
import { extractListingMetadata,fetchListingMetadata,isPrivateAddress } from "@/lib/listing-metadata";

describe("listing metadata",()=>{
  beforeEach(()=>{vi.clearAllMocks();mocks.lookup.mockResolvedValue([{address:"8.8.8.8",family:4}]);});afterEach(()=>vi.unstubAllGlobals());
  it.each(["127.0.0.1","10.0.0.1","172.16.0.1","192.168.1.1","169.254.2.3","100.64.0.1","224.0.0.1","::1","::","fc00::1","fd00::1","fe80::1","fe90::1","fea0::1","feb0::1","::ffff:127.0.0.1"])("blocks private address %s",(address)=>expect(isPrivateAddress(address)).toBe(true));
  it.each(["8.8.8.8","1.1.1.1","2606:4700:4700::1111"])("allows public address %s",(address)=>expect(isPrivateAddress(address)).toBe(false));
  it("extracts safe Open Graph fields and detects the platform",()=>{const html=`<html><head><meta property="og:title" content="Beach &amp; BBQ Villa"><meta property="og:image" content="https://images.example.com/stay.jpg"><meta name="og:locality" content="North Goa"></head></html>`;expect(extractListingMetadata(html,"https://www.airbnb.com/rooms/123")).toEqual({platform:"AIRBNB",propertyName:"Beach & BBQ Villa",imageUrl:"https://images.example.com/stay.jpg",location:"North Goa"})});
  it("uses Twitter and title fallbacks and rejects an insecure image",()=>{expect(extractListingMetadata(`<meta name="twitter:title" content="Twitter Stay"><meta name="twitter:image" content="http://example.com/a.jpg">`,"https://example.com/stay")).toEqual({platform:"OTHER",propertyName:"Twitter Stay"});expect(extractListingMetadata(`<title>Simple &#39;Stay&#39;</title>`,"https://example.com/stay").propertyName).toBe("Simple 'Stay'")});
  it("fetches a public HTML preview",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(`<meta property="og:title" content="Fetched Stay">`,{status:200,headers:{"content-type":"text/html"}})));expect(await fetchListingMetadata("https://example.com/stay")).toMatchObject({propertyName:"Fetched Stay",platform:"OTHER"})});
  it.each(["file:///etc/passwd","https://user:pass@example.com","https://example.com:3000"])("rejects unsafe URL %s",async(url)=>await expect(fetchListingMetadata(url)).rejects.toThrow("Only public"));
  it("rejects unavailable and private DNS results",async()=>{mocks.lookup.mockResolvedValueOnce([]);await expect(fetchListingMetadata("https://example.com")).rejects.toThrow("private or unavailable");mocks.lookup.mockResolvedValueOnce([{address:"127.0.0.1",family:4}]);await expect(fetchListingMetadata("https://example.com")).rejects.toThrow("private or unavailable")});
  it("follows a validated redirect",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(new Response(null,{status:302,headers:{location:"/final"}})).mockResolvedValueOnce(new Response("<title>Final</title>",{headers:{"content-type":"text/html"}}));vi.stubGlobal("fetch",fetchMock);expect(await fetchListingMetadata("https://example.com/start")).toMatchObject({propertyName:"Final"});expect(mocks.lookup).toHaveBeenCalledTimes(2)});
  it("rejects a redirect without a location",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(null,{status:302})));await expect(fetchListingMetadata("https://example.com")).rejects.toThrow("without a destination")});
  it("rejects too many redirects",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(null,{status:302,headers:{location:"/again"}})));await expect(fetchListingMetadata("https://example.com")).rejects.toThrow("too many times")});
  it("reports provider errors and non-HTML responses",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response("no",{status:403,headers:{"content-type":"text/html"}})));await expect(fetchListingMetadata("https://example.com")).rejects.toThrow("returned 403");vi.stubGlobal("fetch",vi.fn(async()=>new Response("{}",{headers:{"content-type":"application/json"}})));await expect(fetchListingMetadata("https://example.com")).rejects.toThrow("did not return a web page")});
  it("limits the downloaded page size",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response("x".repeat(1_000_001),{headers:{"content-type":"text/html"}})));await expect(fetchListingMetadata("https://example.com")).rejects.toThrow("too large")});
});
