import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
import { parseListingUrl } from "@/lib/listing-parser";
import type { ListingPlatform } from "@/lib/types";

export type ListingMetadata={propertyName?:string;imageUrl?:string;location?:string;rating?:number;reviewCount?:number;platform:ListingPlatform};
export function isPrivateAddress(address:string){const normalized=address.toLowerCase();if(normalized==="::1"||normalized==="::"||normalized.startsWith("fc")||normalized.startsWith("fd")||normalized.startsWith("fe8")||normalized.startsWith("fe9")||normalized.startsWith("fea")||normalized.startsWith("feb"))return true;const ipv4=normalized.startsWith("::ffff:")?normalized.slice(7):normalized;if(isIP(ipv4)!==4)return false;const[a,b]=ipv4.split(".").map(Number);return a===0||a===10||a===127||a>=224||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168);}
async function assertPublicUrl(value:string){const url=new URL(value);if(!["http:","https:"].includes(url.protocol)||url.username||url.password||url.port&&!['80','443'].includes(url.port))throw new Error("Only public HTTP or HTTPS listing links are supported.");const addresses=await lookup(url.hostname,{all:true});if(!addresses.length||addresses.some((item)=>isPrivateAddress(item.address)))throw new Error("The listing link resolves to a private or unavailable address.");return url;}
const decode=(value:string)=>value.replaceAll("&amp;","&").replaceAll("&quot;",'"').replaceAll("&#39;", "'").replaceAll("&lt;","<").replaceAll("&gt;",">").trim();
const meta=(html:string,key:string)=>{for(const tag of html.match(/<meta\s+[^>]*>/gi)??[]){const attributes=Object.fromEntries([...tag.matchAll(/([\w:-]+)\s*=\s*["']([^"']*)["']/g)].map((match)=>[match[1].toLowerCase(),decode(match[2])]));if(attributes.property?.toLowerCase()===key||attributes.name?.toLowerCase()===key)return attributes.content;}return undefined;};
export function extractListingMetadata(html:string,url:string):ListingMetadata{const parsed=parseListingUrl(url);const title=meta(html,"og:title")??meta(html,"twitter:title")??html.match(/<title[^>]*>([^<]+)<\/title>/i)?.[1];const image=meta(html,"og:image")??meta(html,"twitter:image");const location=meta(html,"place:location:address")??meta(html,"og:locality");return{platform:parsed.platform,...(title&&{propertyName:decode(title).slice(0,160)}),...(image&&image.startsWith("https://")&&{imageUrl:image}),...(location&&{location:location.slice(0,200)})};}
async function bodyWithLimit(response:Response,limit=1_000_000){if(!response.body)return"";const reader=response.body.getReader();const decoder=new TextDecoder();let size=0,result="";while(true){const{done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit){await reader.cancel();throw new Error("The listing page is too large to import safely.");}result+=decoder.decode(value,{stream:true});}return result+decoder.decode();}
export async function fetchListingMetadata(value:string):Promise<ListingMetadata>{let url=await assertPublicUrl(value);for(let redirects=0;redirects<=3;redirects++){const response=await fetch(url,{redirect:"manual",signal:AbortSignal.timeout(8_000),headers:{"User-Agent":"Roamly-Link-Preview/1.0","Accept":"text/html,application/xhtml+xml"}});if(response.status>=300&&response.status<400){const location=response.headers.get("location");if(!location)throw new Error("The listing redirected without a destination.");url=await assertPublicUrl(new URL(location,url).toString());continue;}if(!response.ok)throw new Error(`The listing site returned ${response.status}.`);if(!response.headers.get("content-type")?.toLowerCase().includes("text/html"))throw new Error("The link did not return a web page.");return extractListingMetadata(await bodyWithLimit(response),url.toString());}throw new Error("The listing redirected too many times.");}
