import { describe,expect,it } from "vitest";
import { calculateRecommendations } from "@/lib/recommendations";
import type { Amenity,Listing,ParticipantPreference,Preference,Vote } from "@/lib/types";

const listing=(id:string,overrides:Partial<Listing>={}):Listing=>({id,tripId:"trip",url:"https://example.com",platform:"OTHER",propertyName:"Stay",imageUrl:null,totalPrice:100,currency:"INR",maxGuests:4,bedrooms:2,beds:2,bathrooms:2,rating:4,reviewCount:10,location:"Town",distanceNote:null,notes:null,tags:[],createdAt:"",updatedAt:"",...overrides});
const preferences:Preference[]=["lowest-price","swimming-pool","near-beach","more-bedrooms","more-bathrooms","high-rating","breakfast","kitchen","parking","private-villa","good-location","unknown"].map((key,index)=>({id:`p${index}`,key,label:key,description:null,createdAt:""}));
const choices:ParticipantPreference[]=preferences.map((preference,index)=>({participantId:"person",preferenceId:preference.id,importance:index===11?"NOT_IMPORTANT":"IMPORTANT",createdAt:"",updatedAt:""}));
const amenities:Amenity[]=["Swimming Pool","Beach Access","Breakfast","Kitchen","Parking","Private Property"].map((label,index)=>({id:`a${index}`,key:`a${index}`,label}));
describe("recommendations",()=>{
  it("uses only votes when no preferences are active",()=>{const stay=listing("one");const votes=[{id:"v",participantId:"p",listingId:"one",value:"LOVE",createdAt:"",updatedAt:""}] satisfies Vote[];expect(calculateRecommendations({listings:[stay],amenities:[],listingAmenities:[],votes,participantCount:1,preferences:[],participantPreferences:[]}).get("one")).toEqual({voteScore:100,preferenceScore:null,combinedScore:100,preferenceCount:0})});
  it("scores all supported preference signals and weights them with votes",()=>{const cheap=listing("cheap",{propertyName:"Private Villa",totalPrice:100,bedrooms:4,bathrooms:4,rating:5,location:"Near beach",distanceNote:"walking distance",tags:["Great location","Easy travel"]});const costly=listing("costly",{totalPrice:300,bedrooms:1,bathrooms:1,rating:2});const links=amenities.map((amenity)=>({listingId:"cheap",amenityId:amenity.id}));const scores=calculateRecommendations({listings:[cheap,costly],amenities,listingAmenities:links,votes:[],participantCount:2,preferences,participantPreferences:choices});expect(scores.get("cheap")?.preferenceScore).toBe(100);expect(scores.get("cheap")?.combinedScore).toBe(25);expect(scores.get("costly")!.preferenceScore).toBeLessThan(30);expect(scores.get("cheap")?.preferenceCount).toBe(11)});
  it("handles equal prices and missing optional listing data",()=>{const result=calculateRecommendations({listings:[listing("a",{bedrooms:null,bathrooms:null,rating:null}),listing("b")],amenities:[],listingAmenities:[],votes:[],participantCount:0,preferences:[preferences[0]],participantPreferences:[choices[0]]});expect(result.get("a")?.preferenceScore).toBe(100)});
  it.each([["private-property","Private Property"],["wifi","Wi-Fi"],["air-conditioning","Air Conditioning"]])("matches the %s default preference",(key,label)=>{const preference={id:"extra",key,label:key,description:null,createdAt:""};const choice={participantId:"person",preferenceId:"extra",importance:"MUST_HAVE" as const,createdAt:"",updatedAt:""};const amenity={id:"extra-amenity",key,label};const result=calculateRecommendations({listings:[listing("stay"),listing("other")],amenities:[amenity],listingAmenities:[{listingId:"stay",amenityId:amenity.id}],votes:[],participantCount:1,preferences:[preference],participantPreferences:[choice]});expect(result.get("stay")?.preferenceScore).toBe(100);expect(result.get("other")?.preferenceScore).toBe(0)});
  it("ignores orphaned choices and safely scores an unknown active preference",()=>{const preference={id:"known",key:"future-signal",label:"Future",description:null,createdAt:""};const result=calculateRecommendations({listings:[listing("stay")],amenities:[],listingAmenities:[],votes:[],participantCount:1,preferences:[preference],participantPreferences:[{participantId:"p",preferenceId:"missing",importance:"IMPORTANT",createdAt:"",updatedAt:""},{participantId:"p",preferenceId:"known",importance:"IMPORTANT",createdAt:"",updatedAt:""}]});expect(result.get("stay")?.preferenceScore).toBe(0)});
});
