import { calculateVoteScore } from "@/lib/ranking";
import type { Amenity,Listing,ListingAmenity,ParticipantPreference,Preference,Vote } from "@/lib/types";

const importanceWeight={NOT_IMPORTANT:0,NICE_TO_HAVE:1,IMPORTANT:2,MUST_HAVE:4} as const;
export type RecommendationScore={voteScore:number;preferenceScore:number|null;combinedScore:number;preferenceCount:number};

export function calculateRecommendations(input:{listings:Listing[];amenities:Amenity[];listingAmenities:ListingAmenity[];votes:Vote[];participantCount:number;preferences:Preference[];participantPreferences:ParticipantPreference[]}):Map<string,RecommendationScore>{
  const prices=input.listings.map((item)=>item.totalPrice);const minPrice=Math.min(...prices);const maxPrice=Math.max(...prices);const maxBedrooms=Math.max(1,...input.listings.map((item)=>item.bedrooms??0));const maxBathrooms=Math.max(1,...input.listings.map((item)=>item.bathrooms??0));
  const preferenceById=new Map(input.preferences.map((item)=>[item.id,item]));
  const active=input.participantPreferences.flatMap((choice)=>{const preference=preferenceById.get(choice.preferenceId);const weight=importanceWeight[choice.importance];return preference&&weight>0?[{key:preference.key,weight}]:[]});
  const scores=new Map<string,RecommendationScore>();
  for(const listing of input.listings){const amenityIds=input.listingAmenities.filter((item)=>item.listingId===listing.id).map((item)=>item.amenityId);const amenityText=input.amenities.filter((item)=>amenityIds.includes(item.id)).map((item)=>item.label.toLowerCase()).join(" ");const searchable=[listing.propertyName,listing.location,listing.distanceNote??"",...(listing.tags??[])].join(" ").toLowerCase();const satisfaction=(key:string):number=>{switch(key){case"lowest-price":return maxPrice===minPrice?1:(maxPrice-listing.totalPrice)/(maxPrice-minPrice);case"swimming-pool":return /pool/.test(amenityText)?1:0;case"near-beach":return /beach/.test(`${amenityText} ${searchable}`)?1:0;case"more-bedrooms":return(listing.bedrooms??0)/maxBedrooms;case"more-bathrooms":return(listing.bathrooms??0)/maxBathrooms;case"high-rating":return(listing.rating??0)/5;case"breakfast":return/breakfast/.test(amenityText)?1:0;case"kitchen":return/kitchen/.test(amenityText)?1:0;case"parking":return/parking/.test(amenityText)?1:0;case"private-villa":return/private|villa/.test(`${amenityText} ${searchable}`)?1:0;case"good-location":return/great location|easy travel|walking distance|near |close/.test(searchable)?1:.25;default:return 0;}};const totalWeight=active.reduce((sum,item)=>sum+item.weight,0);const matched=active.reduce((sum,item)=>sum+satisfaction(item.key)*item.weight,0);const preferenceScore=totalWeight?Math.round(matched/totalWeight*100):null;const voteScore=calculateVoteScore(input.votes.filter((vote)=>vote.listingId===listing.id),input.participantCount);const combinedScore=preferenceScore==null?voteScore:Math.round(voteScore*.75+preferenceScore*.25);scores.set(listing.id,{voteScore,preferenceScore,combinedScore,preferenceCount:active.length});}
  return scores;
}
