"use client";

import { useActionState } from "react";
import { Check,LoaderCircle,Save } from "lucide-react";
import { savePreferences } from "@/actions/preferences";
import { initialFormState } from "@/lib/form-state";
import type { Preference,PreferenceImportance } from "@/lib/types";

const choices:[PreferenceImportance,string,string][]=[["NOT_IMPORTANT","Not important","No effect on recommendations"],["NICE_TO_HAVE","Nice to have","A small preference"],["IMPORTANT","Important","Meaningfully affects the ranking"],["MUST_HAVE","Must have","Strongest preference weight"]];
export function PreferencesForm({inviteCode,preferences,current}:{inviteCode:string;preferences:Preference[];current:Record<string,PreferenceImportance>}){const action=savePreferences.bind(null,inviteCode);const[state,formAction,pending]=useActionState(action,initialFormState);return <form action={formAction}>{state.message&&<div role="status" className="mb-5 flex items-center gap-2 rounded-xl bg-[#e7f1ed] px-4 py-3 text-sm font-bold text-[#285f54]"><Check size={16}/>{state.message}</div>}<div className="space-y-3">{preferences.map((preference)=><div key={preference.id} className="grid gap-3 rounded-2xl border border-[#e3e0d8] bg-white p-4 sm:grid-cols-[1fr_14rem] sm:items-center"><div><label htmlFor={`preference_${preference.id}`} className="font-extrabold">{preference.label}</label>{preference.description&&<p className="mt-1 text-sm text-[#71807c]">{preference.description}</p>}</div><select id={`preference_${preference.id}`} name={`preference_${preference.id}`} defaultValue={current[preference.id]??"NOT_IMPORTANT"} className="min-h-12 w-full rounded-xl border border-[#dcded8] bg-white px-3.5 text-[16px] font-semibold outline-none focus:border-[#1f7168] focus:ring-4 focus:ring-[#1f7168]/10">{choices.map(([value,label,description])=><option key={value} value={value}>{label} — {description}</option>)}</select></div>)}</div><button disabled={pending} className="mt-6 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-full bg-[#e85d3f] px-6 font-bold text-white shadow-[0_12px_28px_rgba(232,93,63,.2)] disabled:opacity-70 sm:w-auto">{pending?<LoaderCircle size={18} className="animate-spin"/>:<Save size={18}/>}Save my preferences</button></form>}
