/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { Bath, BedDouble, ExternalLink, MapPin, MessageCircle, Pencil, Star, Users } from "lucide-react";
import { DeleteListingButton } from "@/components/listing/DeleteListingButton";
import { VoteButtons } from "@/components/voting/VoteButtons";
import { formatMoney } from "@/lib/format";
import type { Amenity, Listing, VoteValue } from "@/lib/types";

const platformLabels = { AIRBNB:"Airbnb",BOOKING:"Booking.com",AGODA:"Agoda",MAKEMYTRIP:"MakeMyTrip",GOIBIBO:"Goibibo",DIRECT:"Direct",OTHER:"Other" } as const;
const platformColors = { AIRBNB:"bg-[#fff0f0] text-[#c83d4c]",BOOKING:"bg-[#eaf2ff] text-[#245ea8]",AGODA:"bg-[#f2edff] text-[#6545ad]",MAKEMYTRIP:"bg-[#fff1e6] text-[#ae4d24]",GOIBIBO:"bg-[#e9f5ff] text-[#256785]",DIRECT:"bg-[#e8f4ee] text-[#28725d]",OTHER:"bg-[#f0ede7] text-[#625e57]" } as const;
type CardListing = Listing & { amenities:Amenity[]; voteCounts:Record<VoteValue,number>; currentVote:VoteValue|null; commentCount:number };

export function ListingCard({ listing, travellerCount, inviteCode, isCreator, selected, canVote }: { listing:CardListing; travellerCount:number; inviteCode:string; isCreator:boolean; selected:boolean; canVote:boolean }) {
  const detailParts = [listing.bedrooms == null ? null : `${listing.bedrooms} bedroom${listing.bedrooms===1?"":"s"}`,listing.bathrooms == null ? null : `${listing.bathrooms} bathroom${listing.bathrooms===1?"":"s"}`,`${listing.maxGuests} guests`].filter(Boolean);
  return <article className="group overflow-hidden rounded-[1.65rem] border border-[#e3e0d8] bg-white shadow-[0_12px_38px_rgba(35,61,55,.07)] transition hover:-translate-y-1 hover:shadow-[0_20px_48px_rgba(35,61,55,.12)]">
    <div className="relative aspect-[4/3] overflow-hidden bg-[#e8efeb]">{listing.imageUrl ? <img src={listing.imageUrl} alt={listing.propertyName} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" loading="lazy" referrerPolicy="no-referrer"/> : <div className="grid h-full place-items-center bg-[radial-gradient(circle_at_top_right,#c8e4dc,transparent_45%),linear-gradient(145deg,#edf2ee,#dce5df)] text-[#6d837c]"><BedDouble size={46} strokeWidth={1.4}/></div>}<span className={`absolute left-4 top-4 rounded-full px-3 py-1.5 text-xs font-extrabold shadow-sm ${platformColors[listing.platform]}`}>{platformLabels[listing.platform]}</span>{selected && <span className="absolute right-4 top-4 rounded-full bg-[#18342f] px-3 py-1.5 text-xs font-extrabold text-white">🏆 Selected stay</span>}</div>
    <div className="p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-xl font-bold tracking-[-.02em]">{listing.propertyName}</h2><p className="mt-1 flex items-center gap-1.5 truncate text-sm text-[#71807c]"><MapPin className="shrink-0" size={15}/><span className="truncate">{listing.location}</span></p></div>{listing.rating != null && <span className="flex shrink-0 items-center gap-1 text-sm font-bold"><Star size={15} fill="#e85d3f" className="text-[#e85d3f]"/>{listing.rating}{listing.reviewCount != null && <span className="font-normal text-[#8a9692]">({listing.reviewCount})</span>}</span>}</div>
      <div className="mt-5 flex items-end justify-between gap-3"><div><p className="text-xl font-extrabold">{formatMoney(listing.totalPrice,listing.currency)} <span className="text-sm font-medium text-[#71807c]">total</span></p><p className="mt-0.5 text-sm font-bold text-[#1f7168]">{formatMoney(listing.totalPrice / travellerCount,listing.currency)} / person</p></div></div>
      <div className="mt-4 flex flex-wrap items-center gap-x-3 gap-y-2 border-y border-[#eeeae3] py-3 text-xs font-semibold text-[#5e6e69]">{listing.bedrooms != null && <span className="flex items-center gap-1"><BedDouble size={14}/>{listing.bedrooms}</span>}{listing.bathrooms != null && <span className="flex items-center gap-1"><Bath size={14}/>{listing.bathrooms}</span>}<span className="flex items-center gap-1"><Users size={14}/>{listing.maxGuests}</span><span className="sr-only">{detailParts.join(", ")}</span>{listing.distanceNote && <span className="min-w-0 truncate">• {listing.distanceNote}</span>}</div>
      {(listing.tags?.length??0)>0&&<div className="mt-4 flex flex-wrap gap-1.5">{listing.tags.slice(0,5).map((tag)=><span key={tag} className="rounded-full bg-[#fff0eb] px-2.5 py-1 text-xs font-extrabold text-[#a94a35]">#{tag}</span>)}</div>}
      {listing.amenities.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{listing.amenities.slice(0,4).map((amenity)=><span key={amenity.id} className="rounded-full bg-[#f1f3ef] px-2.5 py-1 text-xs font-semibold text-[#52645f]">{amenity.label}</span>)}{listing.amenities.length>4 && <span className="rounded-full bg-[#f1f3ef] px-2.5 py-1 text-xs font-semibold text-[#52645f]">+{listing.amenities.length-4}</span>}</div>}
      <VoteButtons inviteCode={inviteCode} listingId={listing.id} initialVote={listing.currentVote} initialCounts={listing.voteCounts} canVote={canVote}/>
      <div className="mt-4 flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-1"><a href={listing.url} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-10 items-center gap-1.5 rounded-full bg-[#18342f] px-4 text-xs font-bold text-white hover:bg-[#285048]">View listing <ExternalLink size={14}/></a><Link href={`/trip/${inviteCode}/listings/${listing.id}`} className="inline-flex min-h-10 items-center gap-1.5 rounded-full px-3 text-xs font-bold hover:bg-[#f1f3ef]"><MessageCircle size={14}/> {listing.commentCount}</Link></div>{isCreator && <div className="flex items-center"><Link href={`/trip/${inviteCode}/listings/${listing.id}/edit`} className="inline-flex min-h-10 items-center gap-1.5 rounded-full px-3 text-xs font-bold hover:bg-[#f1f3ef]"><Pencil size={14}/> Edit</Link><DeleteListingButton inviteCode={inviteCode} listingId={listing.id}/></div>}</div>
    </div>
  </article>;
}
