import Link from "next/link";
import { CalendarDays,MapPin,Plus,Settings,Trophy,Users } from "lucide-react";
import { Logo } from "@/components/brand/Logo";
import { ShareTripButton } from "@/components/trip/ShareTripButton";
import { formatMoney,formatTripDates } from "@/lib/format";
import { getTripLifecycle } from "@/lib/trip-lifecycle";
import type { Trip } from "@/lib/types";

export function TripHeader({trip,isCreator,selectedListingName}:{trip:Trip;isCreator:boolean;selectedListingName?:string}){
  const lifecycle=getTripLifecycle(trip);
  return <><div className="border-b border-[#e8e2d8] bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-8 lg:px-12"><Link href="/"><Logo/></Link><div className="flex items-center gap-2"><ShareTripButton/>{isCreator&&<Link href={`/trip/${trip.inviteCode}/settings`} aria-label="Trip settings" className="hidden size-11 place-items-center rounded-full border border-[#d8dfdc] sm:grid"><Settings size={17}/></Link>}{isCreator&&<Link href={`/trip/${trip.inviteCode}/listings/new`} className="hidden min-h-11 items-center gap-2 rounded-full bg-[#e85d3f] px-5 text-sm font-bold text-white sm:inline-flex"><Plus size={17}/>Add stay</Link>}</div></div></div>{selectedListingName&&<div className="bg-[#18342f] text-white"><div className="mx-auto flex max-w-7xl items-center gap-2 px-4 py-2.5 text-sm font-bold sm:px-8 lg:px-12"><Trophy size={17} className="text-[#f2b65c]"/>Selected stay: <span className="text-[#bfe3da]">{selectedListingName}</span></div></div>}<header className="mx-auto max-w-7xl px-4 pb-7 pt-8 sm:px-8 sm:pb-9 sm:pt-11 lg:px-12"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><div className="mb-2 flex items-center gap-2"><p className="text-sm font-bold text-[#e85d3f]">Your shared shortlist</p>{lifecycle!=="ACTIVE"&&<span className="rounded-full bg-[#e8e5df] px-2.5 py-1 text-xs font-extrabold text-[#52645f]">{lifecycle==="PAST"?"Past":"Completed"}</span>}</div><h1 className="display-font text-4xl font-medium leading-none tracking-[-.035em] sm:text-6xl">{trip.name}</h1><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-sm font-medium text-[#63716d]"><span className="flex items-center gap-1.5"><MapPin size={16}/>{trip.destination}</span><span className="flex items-center gap-1.5"><CalendarDays size={16}/>{formatTripDates(trip.startDate,trip.endDate)}</span><span className="flex items-center gap-1.5"><Users size={16}/>{trip.travellerCount} traveller{trip.travellerCount===1?"":"s"}</span></div>{trip.accommodationBudget&&<p className="mt-3 text-sm text-[#63716d]"><strong className="text-[#29443e]">{formatMoney(trip.accommodationBudget,trip.currency)}</strong> accommodation budget</p>}</div>{isCreator&&<div className="flex gap-2 sm:hidden"><Link href={`/trip/${trip.inviteCode}/settings`} className="grid size-12 place-items-center rounded-full border border-[#d8dfdc]"><Settings size={18}/></Link><Link href={`/trip/${trip.inviteCode}/listings/new`} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#e85d3f] px-6 font-bold text-white"><Plus size={18}/>Add stay</Link></div>}</div></header></>;
}
